Feature/kasm 6788 update build
kasmtech/noVNC pull request #121
Opened 2024-12-30 20:30 UTC by thelamer

This still needs work for the secondary displays, for some reason when threading is enabled it generates blank vid rects.

This overhauls the build process to use vite and externalizes dependencies instead of static versions in the repo. 

Same process but everything works on modern nodejs:
```
npm install
npm run build
```

And the resulting UI will be in /dist.

2025-01-08 15:05 UTC, mmcclaskey requested changes

2025-01-08 15:05 UTC, mmcclaskey commented on vnc.html
> +    <script type="module" crossorigin="use-credentials" src="app/ui.js"></script>
The removal of webpack will require build changes in KasmVNC pipelines, so we will need a corresponding MR in KasmVNC for this.

2025-01-08 15:05 UTC, mmcclaskey commented on package-lock.json
should we add this to the .gitignore? We likely want to keep as a build pipeline artifact, but not in git.

2025-01-08 15:05 UTC, mmcclaskey commented on app/ui.js
> +                    UI.forceSetting('enable_threading', event.data.value, false);
There seems to be two new message types: 'set_threading' and 'enable_threading' and they both seem to do the same thing?

2025-01-08 15:05 UTC, mmcclaskey commented on app/ui.js
> +                case 'enable_threading':
We will need a corresponding group setting in Kasm Workspaces and kasmweb change to pass that setting down to noVNC.

2025-01-09 21:11 UTC, thelamer commented on vnc.html
> +    <script type="module" crossorigin="use-credentials" src="app/ui.js"></script>
This is built out to core I will update the commit refs to this feature branch and build out a core image that can be tested. 
docs/DEVELOP.md also needs to be updated but that is still todo as I am working on a unified development container for KasmVNC and noVNC but got distracted with a couple big improvements I discovered while tinkering.

2025-01-09 21:12 UTC, thelamer commented on app/ui.js
> +                case 'enable_threading':
Agreed, but that should not be a blocker for the frontend stuff on the unreleased master branch.

2025-03-09 19:13 UTC, closed without merging